### ISSUE TITLE
[Feature Request] Download file from a folder

### ISSUE THREAD

**Issue by botjaeger** [vatri/Google-Drive-Bundle#4]
It would be great if you can include a feature that can download a file and convert it to csv or something.

**Comment by vatri** [comment]
I agree for Download File action. @botjaeger can you make it? :)

For conversion - I think it doesn't fit to this bundle. This bundle's purpose is kind of Facade pattern...

**Comment by vatri** [comment]
https://developers.google.com/drive/api/v2/manage-downloads#php

**Comment by vatri** [comment]
Resolved in PR #8

**Comment by vatri** [comment]
P.S.

thanks to @MaximeLemolt  : ))
