### ISSUE TITLE
how to get the google console JSON credentials file ?

### ISSUE THREAD

**Issue by ibasaw** [vatri/Google-Drive-Bundle#7]
I want to use your bundle, but there is something i don't understand about the google console JSON credentials file.

I got a google cloud platform account, i can use my google drive on my windows desktop computer.

I want to store files on this drive from my Symfony application with your bundle.

Where on https://console.cloud.google.com/ i can download this credentials json file ?

If I must use a project, what kind of credentials, i have to create ?

key api, ID clients OAuth 2.0, ... ?

Thanks for your help.

**Comment by vatri** [comment]
Hi Sebastien.

1st note that this bundle is for Drive API **Version 2**

I forgot actual steps, but this is what you can start with 

- go to Google Console
- enable API & Services
- create or select project
- create Oauth credentials (image 1 & image 2)
- download file (Image 2)

Maybe I skipped some steps, but in general this is the proccess.

Image 1:
![image](https://user-images.githubusercontent.com/1230120/83723238-a84ca580-a63e-11ea-88be-142d105fd5d1.png)

Image 2:
![Screenshot_20](https://user-images.githubusercontent.com/1230120/83723410-f3ff4f00-a63e-11ea-956b-0fb88c076e53.png)
